name: CI
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: draft
        options:
        - build
        - draft
        - release
jobs:
  read-repo-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Outputs
      id: out
      run: |
        echo "mcpelauncher-ref=$(cat mcpelauncher.commit)" >> $GITHUB_OUTPUT
    outputs:
      mcpelauncher-ref: ${{ steps.out.outputs.mcpelauncher-ref }}
  ci:
    needs: read-repo-files
    if: (!cancelled())
    runs-on: ubuntu-latest
    steps:
    - run: echo "testing workflow validity"
